/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RajasthanRouteImport } from './routes/rajasthan'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PoliticsRouteImport } from './routes/politics'
import { Route as NationalRouteImport } from './routes/national'
import { Route as LiveTvRouteImport } from './routes/live-tv'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as EntertainmentRouteImport } from './routes/entertainment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorSlugRouteImport } from './routes/author.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RajasthanRoute = RajasthanRouteImport.update({
  id: '/rajasthan',
  path: '/rajasthan',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticsRoute = PoliticsRouteImport.update({
  id: '/politics',
  path: '/politics',
  getParentRoute: () => rootRouteImport,
} as any)
const NationalRoute = NationalRouteImport.update({
  id: '/national',
  path: '/national',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTvRoute = LiveTvRouteImport.update({
  id: '/live-tv',
  path: '/live-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const EntertainmentRoute = EntertainmentRouteImport.update({
  id: '/entertainment',
  path: '/entertainment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorSlugRoute = AuthorSlugRouteImport.update({
  id: '/author/$slug',
  path: '/author/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/entertainment': typeof EntertainmentRoute
  '/international': typeof InternationalRoute
  '/jobs': typeof JobsRoute
  '/live-tv': typeof LiveTvRoute
  '/national': typeof NationalRoute
  '/politics': typeof PoliticsRoute
  '/privacy': typeof PrivacyRoute
  '/rajasthan': typeof RajasthanRoute
  '/search': typeof SearchRoute
  '/sports': typeof SportsRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/author/$slug': typeof AuthorSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/entertainment': typeof EntertainmentRoute
  '/international': typeof InternationalRoute
  '/jobs': typeof JobsRoute
  '/live-tv': typeof LiveTvRoute
  '/national': typeof NationalRoute
  '/politics': typeof PoliticsRoute
  '/privacy': typeof PrivacyRoute
  '/rajasthan': typeof RajasthanRoute
  '/search': typeof SearchRoute
  '/sports': typeof SportsRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/author/$slug': typeof AuthorSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/entertainment': typeof EntertainmentRoute
  '/international': typeof InternationalRoute
  '/jobs': typeof JobsRoute
  '/live-tv': typeof LiveTvRoute
  '/national': typeof NationalRoute
  '/politics': typeof PoliticsRoute
  '/privacy': typeof PrivacyRoute
  '/rajasthan': typeof RajasthanRoute
  '/search': typeof SearchRoute
  '/sports': typeof SportsRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/author/$slug': typeof AuthorSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/entertainment'
    | '/international'
    | '/jobs'
    | '/live-tv'
    | '/national'
    | '/politics'
    | '/privacy'
    | '/rajasthan'
    | '/search'
    | '/sports'
    | '/technology'
    | '/terms'
    | '/videos'
    | '/article/$slug'
    | '/author/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/entertainment'
    | '/international'
    | '/jobs'
    | '/live-tv'
    | '/national'
    | '/politics'
    | '/privacy'
    | '/rajasthan'
    | '/search'
    | '/sports'
    | '/technology'
    | '/terms'
    | '/videos'
    | '/article/$slug'
    | '/author/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/entertainment'
    | '/international'
    | '/jobs'
    | '/live-tv'
    | '/national'
    | '/politics'
    | '/privacy'
    | '/rajasthan'
    | '/search'
    | '/sports'
    | '/technology'
    | '/terms'
    | '/videos'
    | '/article/$slug'
    | '/author/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EntertainmentRoute: typeof EntertainmentRoute
  InternationalRoute: typeof InternationalRoute
  JobsRoute: typeof JobsRoute
  LiveTvRoute: typeof LiveTvRoute
  NationalRoute: typeof NationalRoute
  PoliticsRoute: typeof PoliticsRoute
  PrivacyRoute: typeof PrivacyRoute
  RajasthanRoute: typeof RajasthanRoute
  SearchRoute: typeof SearchRoute
  SportsRoute: typeof SportsRoute
  TechnologyRoute: typeof TechnologyRoute
  TermsRoute: typeof TermsRoute
  VideosRoute: typeof VideosRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  AuthorSlugRoute: typeof AuthorSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rajasthan': {
      id: '/rajasthan'
      path: '/rajasthan'
      fullPath: '/rajasthan'
      preLoaderRoute: typeof RajasthanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politics': {
      id: '/politics'
      path: '/politics'
      fullPath: '/politics'
      preLoaderRoute: typeof PoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/national': {
      id: '/national'
      path: '/national'
      fullPath: '/national'
      preLoaderRoute: typeof NationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-tv': {
      id: '/live-tv'
      path: '/live-tv'
      fullPath: '/live-tv'
      preLoaderRoute: typeof LiveTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entertainment': {
      id: '/entertainment'
      path: '/entertainment'
      fullPath: '/entertainment'
      preLoaderRoute: typeof EntertainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$slug': {
      id: '/author/$slug'
      path: '/author/$slug'
      fullPath: '/author/$slug'
      preLoaderRoute: typeof AuthorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EntertainmentRoute: EntertainmentRoute,
  InternationalRoute: InternationalRoute,
  JobsRoute: JobsRoute,
  LiveTvRoute: LiveTvRoute,
  NationalRoute: NationalRoute,
  PoliticsRoute: PoliticsRoute,
  PrivacyRoute: PrivacyRoute,
  RajasthanRoute: RajasthanRoute,
  SearchRoute: SearchRoute,
  SportsRoute: SportsRoute,
  TechnologyRoute: TechnologyRoute,
  TermsRoute: TermsRoute,
  VideosRoute: VideosRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  AuthorSlugRoute: AuthorSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
